# Generated by Django 5.0.6 on 2024-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_imglink', models.CharField(max_length=300)),
                ('book_des', models.TextField()),
                ('book_author', models.CharField(max_length=50)),
                ('book_releaseDate', models.CharField(max_length=20)),
            ],
        ),
    ]
