# Generated by Django 5.0.6 on 2024-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdetail',
            name='news_slug',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='books/'),
        ),
    ]
