# Generated by Django 5.0.6 on 2024-07-06 07:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=50)),
                ('item_imglink', models.CharField(max_length=300)),
                ('item_price', models.CharField(max_length=300)),
                ('item_des', models.TextField()),
                ('item_author', models.CharField(max_length=50)),
                ('item_releaseDate', models.CharField(max_length=20)),
                ('item_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='item_title', unique=True)),
            ],
        ),
    ]
