# Generated by Django 5.0.6 on 2024-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcolumn',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
