# Generated by Django 5.0.6 on 2024-07-06 07:27

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookDB_title', models.CharField(max_length=50)),
                ('bookDB_imglink', models.CharField(max_length=300)),
                ('bookDB_price', models.CharField(max_length=300)),
                ('bookDB_des', models.TextField()),
                ('bookDB_author', models.CharField(max_length=50)),
                ('bookDB_releaseDate', models.CharField(max_length=20)),
                ('bookDB_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='bookDB_title', unique=True)),
            ],
        ),
    ]
